### ISSUE TITLE
Enlarging global_font_size to 30 makes hints completely unreadable

### ISSUE THREAD

**Issue by smedelyan** [Ark2000/PankuConsole#186]
**Godot version:** 4.2.2.stable
**Panku version:** 1.7.9 (from GitHub, not available in AssetStore)

**Describe the bug**
My viewport is set to 4k. The default window is small and the text is also small, so I went ahead and increased size to 30. It displays good, except the hints - they are completely unreadable.

**To Reproduce**
Try these settings and see how things get blurred out.
![image](https://github.com/user-attachments/assets/1c007d3d-904b-4aa3-9f81-700d1922c7ae)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by worron** [comment]
It doesn't look like something viewport resolution or font size related.

Did you set global custom font or custom theme in your project settings?
Can you reproduce the problem on new empty project?

**Comment by smedelyan** [comment]
Hmm, I can't reproduce this in empty project: 
<details><summary>screenshot</summary>
<p>

![image](https://github.com/user-attachments/assets/d689b557-88bf-4610-837e-ff7a44d8ec99)

</p>
</details>

I do have a custom theme that I use on my root GUI control, but I don't believe this should affect Panku... Is there a special place where I can assign a theme / a font to apply to the whole project?

P. S. I also use custom theme for the editor itself, including the font. However, in an empty project this does not affect Panku, so should not be a problem either.

**Comment by smedelyan** [comment]
Ah, sorry, an update: I managed to achieve sort of the same result on an empty project:

<details><summary>screenshot</summary>
<p>

![image](https://github.com/user-attachments/assets/4a171398-3a95-4a5e-b9b0-cac89b79f8b6)


</p>
</details> 

The change that did the trick was to switch the stretch mode of the project from `disabled` to `canvas_items`:
![image](https://github.com/user-attachments/assets/8d51aa40-37cc-4e21-890b-3e4ade7752b5)

Here's the mrp: [panku_font.zip](https://github.com/user-attachments/files/16740735/panku_font.zip)

**Comment by worron** [comment]
Thanks for providing mrp.

If I get it right, the problem appear only when app window heavily downscaled (like 4k -> fullhd on screenshot). Seems like upstream godot issue, so we can't do much here.

![godot_rich_text_label_downscale](https://github.com/user-attachments/assets/4020a303-1e9e-40c8-824b-24bfba49f33f)

As a temporary workaround I only can propose to get rid of bold fonts in panku console theme, since that font type seems most affected. In `res://addons/panku_console/res/panku_console_theme.tres` edit `RichTextLabel` entry `bold_font` and `bold_italic_font` settings to some custom font. It can be godot default open sans `OpenSans-SemiBold.ttf` if you bother to [download it](https://fonts.google.com/specimen/Open+Sans), or just slap empty font variation.

>Is there a special place where I can assign a theme / a font to apply to the whole project?

Yeah, custom theme in project settings affects whole app, including panku console view. It was my first thoughts when I saw the issue, but it ended I was wrong.

**Comment by smedelyan** [comment]
Thank you for the thorough response! I believe the issue is resolved then, so I'm closing at.
Thank's for the help again 🐳
